Feat 136 generic loop
AllenNeuralDynamics/aind-data-transfer pull request #137
Opened 2023-01-07 20:10 UTC by jtyoung84

Closes #136 

- Adds some documentation on Generic Upload Job usage
- Adds script to loop through job params defined in a csv file

2023-01-07 20:31 UTC, jtyoung84 commented
Would appreciate feedback on the README docs.

2023-01-09 17:12 UTC, dyf requested changes
small change

2023-01-09 17:12 UTC, dyf commented on src/aind_data_transfer/jobs/s3_upload_job.py
> +class GenericS3UploadJobs:
Can we call this `GenericS3UPloadJobList` or something? The extra `s` isn't obvious.

2023-01-09 18:51 UTC, dyf approved these changes

2023-01-09 18:53 UTC, merged